### ISSUE TITLE
Work on promotions

### ISSUE THREAD

**Issue by liujiajun** [AY1920S2-CS2102-Team16/Food-Delivery-Service#28]
# TODO
- [x] Rule - Nth order
- [x] Rule - Order total
- [x] Action - Food discount (Percent, Fixed)
- [x] Action - Delivery discount (Fixed) 
- [ ] Testing
- [x] Documentation

**Comment by liujiajun** [comment]
#45 supports managing promotions for both restaurants and admins
